name: AWS EKS Infra Provision

on:
  push:
    branches:
      - modules
  pull_request:
    branches:
      - modules

jobs:
  eks-flux:
    name: 'AWS EKS Deployment'
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: 'eu-west-1'
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEYID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '1.1.0'

      - name: Terraform Init
        run: terraform init ./EKS

      - name: Terraform Plan
        if: github.event_name == 'push'
        run: terraform plan ./EKS

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/modules'
        run: terraform apply -auto-approve ./EKS

