name: AWS EKS Infra Provision

on:
  push:
    branches:
      - modules
  pull_request:
    branches:
      - modules

jobs:
  eks-flux:
    name: 'AWS EKS Deployment'
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: 'eu-west-1'
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEYID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Format
        id: fmt
        working-directory: terraform
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        working-directory: terraform
        run: terraform init

      - name: Terraform Validate
        id: validate
        working-directory: terraform
        run: terraform validate -no-color

      - name: Terraform Plan
        id: plan
        working-directory: terraform
        run: terraform plan -no-color -input=false

      - name: Terraform Apply
        working-directory: terraform
        if: github.ref == 'refs/heads/modules' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false

