name: AWS Infra Provision

on:
  push:
    branches:
    - modules
  pull_request:
    branches:
    - modules

jobs:
  eks-flux:
    defaults:
      run:
        shell: bash

    name: 'AWS EKS Deployments'
    runs-on: ubuntu-latest
    env:

      AWS_DEFAULT_REGION: 'eu-west-1'  
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Terraform Execution
      if: ${{ env.TF_VERBOSE != '' }}
      uses: ./EKS/

