name: AWS INFRA PROVISION

on:
  push:
    branches:
      - modules
  pull_request:
    branches:
      - modules

jobs:
  eks:
    defaults:
      run:
        shell: bash

    name: 'AWS EKS DEPLOYMENT'
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: 'us-west-1'
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESSKEYID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET }}

    steps:
    - name: Checkout
      uses: EKS/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.ACCESSKEYID }}
        aws-secret-access-key: ${{ secrets.SECRET }}
        aws-region: 'us-west-1'

    - name: Debug AWS Credentials
      run: |
        echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"

    - name: Terraform Init
      run: terraform init
      continue-on-error: true

    - name: Terraform Validate
      run: terraform validate
      continue-on-error: true

    - name: Terraform Plan
      run: terraform plan -out=plan.tfplan
      continue-on-error: true

    - name: Terraform Apply
      if: github.ref == 'refs/heads/modules'
      run: terraform apply -auto-approve plan.tfplan
      continue-on-error: true

    - name: Debug - Check Terraform Version
      run: terraform --version

    - name: Debug - Output Terraform Init Log
      run: terraform init -no-color

    - name: Debug - Output Terraform Validate Log
      run: terraform validate -no-color

    - name: Debug - Output Terraform Plan Log
      run: terraform plan -no-color -out=plan.tfplan

    - name: Debug - Output Terraform Apply Log
      if: github.ref == 'refs/heads/modules'
      run: terraform apply -no-color -auto-approve plan.tfplan

